name: Build Tests
on: [pull_request]
jobs:
  jest:
    name: "Jest Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js "13.x"
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: unit_testing/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Installing Node Dependencies
        run: |
          npm install
          cd unit_testing
          npm install
      - name: Lint Example JavaScript
        run: npm run lint
      - name: Running Jest
        run: |
          cd unit_testing
          npm run test
        env:
          CI: true
  jekyll:
    name: "Jekyll Build Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Installing ruby gems
        run: |
          bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - name: Building Site
        run: |
          bundle exec jekyll build
      - name: Running htmlproofer
        run: |
          bundle exec htmlproofer ./_site --assume-extension --check-html --disable-external --url-ignore "/#.*/"
